[ req ]
default_bits        = 2048
default_md          = sha256
prompt              = no
distinguished_name  = dn
req_extensions      = v3_req
string_mask         = utf8only

[ dn ]
C  = FR
ST = PACA
L  = Marseille
O  = MonEntreprise
CN = *.monentreprise.fr

[ req_ext ]
subjectAltName = @alt_names
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
basicConstraints = critical, CA:false

[ v3_req ]
subjectKeyIdentifier 	= hash
basicConstraints     	= critical,CA:false
extendedKeyUsage 		= serverAuth
keyUsage             	= critical,digitalSignature,keyEncipherment
subjectAltName       	= @alt_names

[ server_cert ]
basicConstraints       = critical, CA:false
nsCertType             = server
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid,issuer
keyUsage               = critical, digitalSignature, keyEncipherment
extendedKeyUsage       = serverAuth
subjectAltName         = @alt_names

[ alt_names ]
DNS.1 = *.monentreprise.fr
DNS.2 = monentreprise.fr